-- Supabase SQL Setup for Cart Application
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

-- Create the current_order table for storing cart items
CREATE TABLE IF NOT EXISTS public.current_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    username CHARACTER VARYING NOT NULL DEFAULT 'dummy'::CHARACTER VARYING,
    food_name CHARACTER VARYING NOT NULL DEFAULT 'paani'::CHARACTER VARYING,
    quantity BIGINT NOT NULL,
    CONSTRAINT current_order_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create settings table for admin settings (like visible categories)
CREATE TABLE IF NOT EXISTS public.app_settings (
    id INTEGER PRIMARY KEY DEFAULT 1,
    visible_categories JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert initial settings row
INSERT INTO public.app_settings (id, visible_categories, updated_at)
VALUES (1, '{}'::jsonb, NOW())
ON CONFLICT (id) DO NOTHING;

-- Enable Row Level Security (RLS)
ALTER TABLE public.current_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Create policies for current_order table
CREATE POLICY "Allow anonymous read access" ON public.current_order
    FOR SELECT
    USING (true);

CREATE POLICY "Allow anonymous insert access" ON public.current_order
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow anonymous update access" ON public.current_order
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow anonymous delete access" ON public.current_order
    FOR DELETE
    USING (true);

-- Create policies for app_settings table
CREATE POLICY "Allow anonymous read settings" ON public.app_settings
    FOR SELECT
    USING (true);

CREATE POLICY "Allow anonymous update settings" ON public.app_settings
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow anonymous insert settings" ON public.app_settings
    FOR INSERT
    WITH CHECK (true);

-- Grant permissions to anonymous users
GRANT SELECT, INSERT, UPDATE, DELETE ON public.current_order TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.current_order TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.app_settings TO anon;
GRANT SELECT, INSERT, UPDATE ON public.app_settings TO authenticated;

-- Required for gen_random_uuid() used in transactional archive function
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Transactional function: archive current orders into order_history and clear only archived rows
-- Expects JSON array items with keys: id, username, food_name, quantity, unit_price
CREATE OR REPLACE FUNCTION public.save_and_clear_orders(p_orders JSONB)
RETURNS TABLE(order_batch_id UUID, archived_count INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_batch_id UUID := gen_random_uuid();
BEGIN
    IF p_orders IS NULL OR jsonb_array_length(p_orders) = 0 THEN
        RETURN QUERY SELECT NULL::UUID, 0;
        RETURN;
    END IF;

    INSERT INTO public.order_history (order_batch_id, username, food_name, quantity, unit_price)
    SELECT
        v_batch_id,
        item->>'username',
        item->>'food_name',
        (item->>'quantity')::BIGINT,
        COALESCE((item->>'unit_price')::NUMERIC(10,2), 0.00)
    FROM jsonb_array_elements(p_orders) AS item;

    DELETE FROM public.current_order c
    USING jsonb_array_elements(p_orders) AS item
    WHERE c.id = (item->>'id')::BIGINT;

    RETURN QUERY SELECT v_batch_id, jsonb_array_length(p_orders);
END;
$$;

GRANT EXECUTE ON FUNCTION public.save_and_clear_orders(JSONB) TO anon;
GRANT EXECUTE ON FUNCTION public.save_and_clear_orders(JSONB) TO authenticated;
